feat: call snippet in the background
SAP/code-snippet pull request #129
Opened 2021-05-05 16:25 UTC by NetaMolcho

2021-05-05 17:21 UTC, slavik-lvovsky requested changes
I will review tests when they are ready

2021-05-05 17:21 UTC, slavik-lvovsky commented on packages/backend/package.json
> +  "version": "1.0.1",
Do not change versions. They will be changed automatically

2021-05-05 17:21 UTC, slavik-lvovsky commented on examples/vscode-snippet-contrib/package.json
> +  "version": "1.0.1",
Do not change versions. They will be changed automatically

2021-05-05 17:21 UTC, slavik-lvovsky commented on packages/frontend/package.json
> +  "version": "1.0.1",
Do not change versions. They will be changed automatically

2021-05-05 17:21 UTC, slavik-lvovsky commented on packages/types/package.json
> +  "version": "1.0.1",
Do not change versions. They will be changed automatically

2021-05-10 04:49 UTC, slavik-lvovsky requested changes
please consult with Rima and remove node10 and node12 from .circleci/config/yml

2021-05-10 04:49 UTC, slavik-lvovsky commented on packages/backend/test/code-snippet.spec.ts
> +    let codeSnippetInstanceMock: any;
every mock should be of type SinonMock

2021-05-10 04:49 UTC, slavik-lvovsky commented on packages/backend/test/code-snippet.spec.ts
> +        return expect(e).to.be.equal("");
what error message do we get here ?

2021-05-10 04:49 UTC, slavik-lvovsky commented on packages/backend/test/code-snippet.spec.ts
> +        await codeSnippetInstance["executeCodeSnippet"]({});
add fail("test should fail")

2021-05-10 13:34 UTC, slavik-lvovsky approved these changes

2021-05-10 15:23 UTC, merged

2021-05-11 08:40 UTC, bd82 commented on examples/vscode-snippet-contrib/package.json
> +    "@types/vscode": "1.55.0"
should not this match the version in the engine above?
```
  "engines": {
    "vscode": "^1.44.2"
  },
```

Why did we change it as part of this PR?
Did we miss some API in previous version of the types? 
Won't this mean we need to adjust the `engine` section` as well?

2021-05-11 08:45 UTC, bd82 commented on packages/backend/package.json
> +    "@sap/swa-for-sapbas-vsx": "1.2.15",
it is preferred to not mix a new feature and deps version updating.

2021-05-11 08:53 UTC, bd82 commented on packages/backend/src/code-snippet.ts
> +  private async getDefaultAnswers(): Promise<any> {
- `getDefaultAnswers` --> `computeDefaultAnswers` as this does not seem to be a "getter" and includes non trivial logic

2021-05-11 08:59 UTC, bd82 commented on packages/backend/src/code-snippet.ts
> +        answers[question.name] = question.default;
Does not this line mean that all `answers` would get a `default` of `undefined`
even if no `default` has been provided?

Should we distinguish between no defaults and undefined default?
```javascript
const noDefault = {}
const undefinedDefault = { default: undefined }

Object.keys(noDefault) // --> []
Object.keys(undefinedDefault) // --> ["defaullt"]

```

2021-05-11 09:05 UTC, bd82 commented on packages/backend/src/code-snippet.ts
> +  private async getDefaultAnswers(): Promise<any> {
Because this is the **non-interactive** flow maybe it could even be named
**computeNonInteractiveAnswer** but that is a very long name...

2021-05-11 09:11 UTC, bd82 commented on packages/backend/src/code-snippet.ts
> +      return Promise.reject(errorMessage);
Why do we need Promise.reject?
Is not this equivalent to a simple `throw` in an **async** function?

2021-05-11 09:15 UTC, bd82 commented on packages/backend/src/panels/AbstractWebviewPanel.ts
> +  public async setWebviewPanel(
some changes to this function looks like regressions.
- using `unknown` instead of partial type information.
- using `_.get` instead of **optional chaining**

2021-05-11 09:19 UTC, bd82 commented on packages/backend/src/panels/CodeSnippetPanel.ts
> +    if (_.get(uiOptions, "isNonInteractive", false)) {
you won't need `_.get` if you had a partial type signature for `uiOptions`

2021-05-11 09:30 UTC, bd82 commented on packages/backend/test/code-snippet.spec.ts
> +        expect(error).to.be.equal("No response received.");
you can probably use [chai-as-promised](https://github.com/domenic/chai-as-promised) to avoid building the structure of the error catch/assertion
which is less error prone.

2021-05-13 06:28 UTC, NetaMolcho commented on packages/backend/src/code-snippet.ts
> +    const res = _.defaults(this.uiOptions.contributorInfo.snippetArgs, answers);
I tested what happens if the first argument is undefined, the response will be the second argument

2021-05-13 06:33 UTC, NetaMolcho commented on packages/backend/src/code-snippet.ts
> +    if (_.isEmpty(answers)) {
If they have no questions at all, we get into this isEmpty if