fix: show output does not work, panel serializer does not work
SAP/code-snippet pull request #140
Opened 2021-06-14 11:54 UTC by slavik-lvovsky

2021-06-14 12:17 UTC, alex-gilin requested changes

2021-06-14 12:17 UTC, alex-gilin commented on packages/backend/src/panels/CodeSnippetPanel.ts
>        )}' snippet could not be found.`;
duplicate with getContribInfoFrom()

2021-06-14 12:17 UTC, alex-gilin commented on packages/backend/src/panels/CodeSnippetPanel.ts
> +  private getContribInfoFrom(uiOptions?: unknown) {
signature - return value missing

2021-06-14 12:17 UTC, alex-gilin commented on packages/backend/src/panels/CodeSnippetPanel.ts
> +      throw new Error(errorMessage);
is the same like reject , isn't it ?

2021-06-15 04:34 UTC, slavik-lvovsky commented on packages/backend/src/panels/CodeSnippetPanel.ts
>        )}' snippet could not be found.`;
No, I do not see any duplication here

2021-06-15 04:35 UTC, slavik-lvovsky commented on packages/backend/src/panels/CodeSnippetPanel.ts
> +      throw new Error(errorMessage);
the effect is the same

2021-06-15 06:59 UTC, slavik-lvovsky commented on packages/backend/src/panels/CodeSnippetPanel.ts
> +  private getContribInfoFrom(uiOptions?: unknown) {
Done

2021-06-15 08:22 UTC, alex-gilin approved these changes

2021-06-15 08:40 UTC, bd82 commented on packages/backend/package.json
> +    "*"
👍

2021-06-15 08:41 UTC, bd82 commented on packages/backend/src/panels/CodeSnippetPanel.ts
> +  // uiOptions comming from webview panel serializer looks like: {contributorInfo: {...}, ...}
`coming` (single `m`)

2021-06-15 08:42 UTC, bd82 commented on packages/backend/src/panels/CodeSnippetPanel.ts
> +      // it is save to call resolve several times on same promise
`save` --> `safe`

2021-06-15 08:44 UTC, bd82 commented on packages/backend/src/utils.ts
> +type ResolveFunc<T> = (value: T | PromiseLike<T>) => void;
did not we locate some of these signatures is es5.d.ts (built-in types)?

2021-06-15 08:49 UTC, bd82 commented on packages/backend/src/utils.ts
> +type ResolveFunc<T> = (value: T | PromiseLike<T>) => void;
never mind, it does not seem like the RejectType / ResolveType are easily extractable from there (or at all?)

2021-06-15 10:20 UTC, slavik-lvovsky commented on packages/backend/src/panels/CodeSnippetPanel.ts
> +  // uiOptions comming from webview panel serializer looks like: {contributorInfo: {...}, ...}
Done

2021-06-15 10:20 UTC, slavik-lvovsky commented on packages/backend/src/panels/CodeSnippetPanel.ts
> +      // it is save to call resolve several times on same promise
Done

2021-06-15 10:27 UTC, merged