fix: yeoman-environment version update + code refactor + tests
SAP/code-snippet pull request #52
Opened 2020-11-23 14:24 UTC by slavik-lvovsky

2020-11-23 14:41 UTC, slavik-lvovsky commented
fixes this bug: https://sapjira.wdf.sap.corp/browse/DEVXBUGS-7878

2020-11-23 15:38 UTC, tomer-epstein requested changes

2020-11-23 15:38 UTC, tomer-epstein commented on backend/src/contributors.ts
> +            const api = await Contributors.apiMap.get(contributorId);
feel to me like there is no await for the activate() method.

2020-11-23 15:40 UTC, tomer-epstein commented on backend/src/contributors.ts
> +            const api = await Contributors.apiMap.get(contributorId);
I would like to keep a getApi method.

2020-11-23 15:46 UTC, tomer-epstein commented on backend/src/panels/CodeSnippetPanel.ts
> +				return vscode.window.showErrorMessage("Can not find snippet.");
I consider remove the vscode notification. and only only log it.

2020-11-23 16:11 UTC, tomer-epstein commented on backend/src/panels/CodeSnippetPanel.ts
> +				this.webViewPanel.dispose();
Nice 💯

2020-11-23 19:25 UTC, slavik-lvovsky commented on backend/src/contributors.ts
> +            const api = await Contributors.apiMap.get(contributorId);
extension.activate() returns Thenable, so it is OK to use await

2020-11-24 06:05 UTC, slavik-lvovsky commented on backend/src/contributors.ts
> +            const api = await Contributors.apiMap.get(contributorId);
I have added a new test with activate method

2020-11-24 06:06 UTC, slavik-lvovsky commented on backend/src/panels/CodeSnippetPanel.ts
> +				return vscode.window.showErrorMessage("Can not find snippet.");
We talked to leave it, didn't we ?

2020-11-24 06:11 UTC, tomer-epstein requested changes

2020-11-24 06:11 UTC, tomer-epstein commented on backend/src/contributors.ts
> +            const api = await Contributors.apiMap.get(contributorId);
const apiPromise = Contributors.apiMap.get(contributorId);
            const api = await

2020-11-24 06:13 UTC, slavik-lvovsky commented on backend/src/contributors.ts
> +            const api = await Contributors.apiMap.get(contributorId);
Done

2020-11-24 06:24 UTC, tomer-epstein commented on backend/src/contributors.ts
> +        return (extension.isActive ? extension.exports : extension.activate());
extension.exports is not a promise, but we can keep the name.

2020-11-24 07:31 UTC, tomer-epstein commented
as we just discuss. lets activate (if not already active) only when trying to get the snippet, and then update the apiMap.

2020-11-24 12:26 UTC, tomer-epstein requested changes

2020-11-24 12:26 UTC, tomer-epstein commented on backend/src/contributors.ts
> +                const extensionId = `${extensionPublisher}.${extensionName}`;
private static getExtensionId(extension: vscode.Extension<any>)

2020-11-24 12:26 UTC, tomer-epstein commented on backend/src/panels/CodeSnippetPanel.ts
> +		const contributerInfo = _.get(uiOptions, "contributerInfo", uiOptions);
This will break all code-snippet contributors.

2020-11-24 12:26 UTC, tomer-epstein commented on backend/src/panels/CodeSnippetPanel.ts
> +				{ messages: this.messages, snippet, contributerInfo});
?

2020-11-24 12:26 UTC, tomer-epstein commented on backend/src/contributors.ts
> +        return (extension.isActive ? Promise.resolve(extension.exports) : extension.activate());
no need to wrap extension.exports with Promise.

2020-11-24 12:26 UTC, tomer-epstein commented on backend/src/contributors.ts
> +        if (extension) {
what if extension not found?

2020-11-24 12:42 UTC, slavik-lvovsky commented on backend/src/contributors.ts
> +        if (extension) {
in this case tab is closed and we show error message

2020-11-24 12:46 UTC, tomer-epstein commented on backend/src/contributors.ts
> +        const snippetName = _.get(contributerInfo, "snippetName");
move into the try block

2020-11-24 12:47 UTC, slavik-lvovsky commented on backend/src/contributors.ts
> +                const extensionId = `${extensionPublisher}.${extensionName}`;
done

2020-11-24 12:47 UTC, slavik-lvovsky commented on backend/src/contributors.ts
> +        return (extension.isActive ? Promise.resolve(extension.exports) : extension.activate());
done

2020-11-24 13:07 UTC, slavik-lvovsky commented on backend/src/contributors.ts
> +        const snippetName = _.get(contributerInfo, "snippetName");
done

2020-11-24 13:09 UTC, tomer-epstein submitted a review, later dismissed

2020-11-24 13:14 UTC, tomer-epstein approved these changes

2020-11-24 13:14 UTC, merged